[package]
name = "fp_ecs"
version = "0.0.0"
edition = "2024"
description = "A basic ecs implementation"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
